#!/bin/bash

if [[ x$JB_ROOT_PATH != x"" ]]; then
    JBROOT="/var/jb"
else
    JBROOT=""
fi
mkdir -p "$JBROOT/var/mobile/Library/Caches/com.udevs.dockx" || true
chown mobile:mobile "$JBROOT/var/mobile/Library/Caches/com.udevs.dockx"
chmod 0755 "$JBROOT/var/mobile/Library/Caches/com.udevs.dockx"

exit 0
